name: data_generator
channels:
- defaults
dependencies:
- ca-certificates=2017.08.26=h1d4fec5_0
- certifi=2017.11.5=py36hf29ccca_0
- intel-openmp=2018.0.0=hc7b2577_8
- libedit=3.1=heed3624_0
- libffi=3.2.1=hd88cf55_4
- libgcc-ng=7.2.0=h7cc24e2_2
- libgfortran-ng=7.2.0=h9f7466a_2
- libstdcxx-ng=7.2.0=h7a57d05_2
- mkl=2018.0.1=h19d6760_4
- ncurses=6.0=h9df7e31_2
- numpy=1.14.0=py36h3dfced4_0
- openssl=1.0.2n=hb7f436b_0
- pandas=0.22.0=py36hf484d3e_0
- pip=9.0.1=py36h6c6f9ce_4
- python=3.6.4=hc3d631a_1
- python-dateutil=2.6.1=py36h88d3b88_1
- pytz=2017.3=py36h63b9c63_0
- pyyaml=3.12=py36hafb9ca4_1
- readline=7.0=ha6073c6_4
- setuptools=38.4.0=py36_0
- six=1.11.0=py36h372c433_1
- sqlite=3.21.0=h1bed415_0
- tk=8.6.7=hc745277_3
- wheel=0.30.0=py36hfd4bba0_1
- xz=5.2.3=h55aa19d_2
- yaml=0.1.7=had09818_2
- zlib=1.2.11=ha838bed_2
